import os
import pytest
from app.services.scanner.rules.rust_rule import RustRule


def test_detect_language_with_cargo_toml():
    assert RustRule.detect_language(["Cargo.toml"]) == True


def test_detect_language_without_cargo_toml():
    assert RustRule.detect_language(["package.json"]) == False


def test_detect_basic_rust_app(tmpdir):
    # 创建 Cargo.toml
    with open(os.path.join(str(tmpdir), "Cargo.toml"), "w") as f:
        f.write('[package]\nname = "my-app"\nversion = "0.1.0"\nedition = "2021"\n')
    # 创建 src/main.rs
    src_dir = os.path.join(str(tmpdir), "src")
    os.makedirs(src_dir)
    with open(os.path.join(src_dir, "main.rs"), "w") as f:
        f.write('fn main() { println!("Hello, world!"); }')

    result = RustRule.detect(str(tmpdir))
    assert result["language"] == "rust"
    assert result["entry_point"] == "src/main.rs"
    assert result["package_manager"] == "cargo"
    assert result["build_command"] == "cargo build --release"
    assert result["start_command"] == "./target/release/my-app"
    assert result["port"] == 8080


def test_detect_actix_web_framework(tmpdir):
    with open(os.path.join(str(tmpdir), "Cargo.toml"), "w") as f:
        f.write('[package]\nname = "actix-app"\nversion = "0.1.0"\n[dependencies]\nactix-web = "4"\n')
    src_dir = os.path.join(str(tmpdir), "src")
    os.makedirs(src_dir)
    with open(os.path.join(src_dir, "main.rs"), "w") as f:
        f.write('fn main() {}')

    result = RustRule.detect(str(tmpdir))
    assert result["framework"] == "actix-web"


def test_detect_rocket_framework(tmpdir):
    with open(os.path.join(str(tmpdir), "Cargo.toml"), "w") as f:
        f.write('[package]\nname = "rocket-app"\nversion = "0.1.0"\n[dependencies]\nrocket = "0.5"\n')
    src_dir = os.path.join(str(tmpdir), "src")
    os.makedirs(src_dir)
    with open(os.path.join(src_dir, "main.rs"), "w") as f:
        f.write('fn main() {}')

    result = RustRule.detect(str(tmpdir))
    assert result["framework"] == "rocket"


def test_detect_axum_framework(tmpdir):
    with open(os.path.join(str(tmpdir), "Cargo.toml"), "w") as f:
        f.write('[package]\nname = "axum-app"\nversion = "0.1.0"\n[dependencies]\naxum = "0.7"\n')
    src_dir = os.path.join(str(tmpdir), "src")
    os.makedirs(src_dir)
    with open(os.path.join(src_dir, "main.rs"), "w") as f:
        f.write('fn main() {}')

    result = RustRule.detect(str(tmpdir))
    assert result["framework"] == "axum"


def test_detect_cargo_lock_package_manager(tmpdir):
    with open(os.path.join(str(tmpdir), "Cargo.toml"), "w") as f:
        f.write('[package]\nname = "test-app"\n')
    with open(os.path.join(str(tmpdir), "Cargo.lock"), "w") as f:
        f.write("# This file is automatically @generated by Cargo.\n")
    src_dir = os.path.join(str(tmpdir), "src")
    os.makedirs(src_dir)
    with open(os.path.join(src_dir, "main.rs"), "w") as f:
        f.write('fn main() {}')

    result = RustRule.detect(str(tmpdir))
    assert result["package_manager"] == "cargo"


def test_detect_without_src_main(tmpdir):
    """Cargo.toml 存在但没有 src/main.rs，entry_point 应为 None"""
    with open(os.path.join(str(tmpdir), "Cargo.toml"), "w") as f:
        f.write('[package]\nname = "no-entry"\n')
    # 不创建 src 目录
    result = RustRule.detect(str(tmpdir))
    assert result["entry_point"] is None


def test_detect_without_cargo_toml(tmpdir):
    """没有 Cargo.toml 时返回默认值"""
    result = RustRule.detect(str(tmpdir))
    assert result["language"] == "rust"
    assert result["framework"] == ""
    assert result["entry_point"] is None
    assert result["package_manager"] == "cargo"
    assert result["build_command"] == "cargo build --release"
    assert result["start_command"] is None
    assert result["port"] == 8080


def test_language_id():
    assert RustRule.language_id() == "rust"


def test_get_template_name():
    assert RustRule.get_template_name() == "rust_template"
